language: python
sudo: required
python:
  - "2.7"
  - "3.3"
  - "3.4"
install: 
  - add-apt-repository -y ppa:tuleu/precise-backports
  - sudo apt-get update
  - sudo apt-get install git
  - pip install -r requirements.txt
script: 
  - python -m unittest discover
